###############################################################################
# WARNING:
# This file should be added to your .gitignore and never committed.
# For demo purposes it is added to source control.
###############################################################################

production:
  example:
    DATABASE_URL: postgres://username:password@YOUR_PRODUCTION_HOST:5432/app--db  # source using s3, puppet, vault, etc